### ISSUE TITLE
Handle invalid music files

### ISSUE THREAD

**Issue by promythyus** [thebigmunch/gmusicapi-scripts#29]
I have my Music folder shared by SMB and AFP (host being Debian Linux, where I am running the py scripts), and I browse the folder on Mac OS X over the network. This creates ".AppleDouble" folders and "._" files, eg.
```
ArtistFolder/AlbumFolder/01 - SongName.mp3
ArtistFolder/AlbumFolder/.AppleDouble/01 - SongName.mp3
ArtistFolder/AlbumFolder/._01 - SongName.mp3
```

These are included because of the .mp3 filename, but are not true MP3 files and cause mutagen.mp3 to raise HeaderNotFoundError (see this gist: https://gist.github.com/anonymous/7a8797dd1b34c13fa0d5).

This obviously can be solved by using -e to exclude .AppleDouble and ._ files, but the problem is finding and detecting these files. Since I'm only familiar with this script by looking at the source for 5 seconds, I just did this in gmwrapper.py's compare_song_collections:
```python

	for src_song in src_songs:
		try:
			src_key = create_song_key(src_song)
			src_songs_keyed[src_key] = src_song
		except mutagen.mp3.HeaderNotFoundError:
			print("MP3 Header Error on file: ", src_song)

	for dest_song in dest_songs:
		try:
			dest_key = create_song_key(dest_song)
			dest_songs_keyed[dest_key] = dest_song
		except mutagen.mp3.HeaderNotFoundError:
			print("MP3 Header Error on file: ", dest_song)
```

This way the user will be shown what file is causing the error, and the loop continues to process files. Not sure if this is the best way to do this here, so I'll leave that up to whoever wants to do the fix for this :)

**Comment by thebigmunch** [comment]
There was another issue about this. Also, try out the devel tree which uses my [standalone wrapper](https://github.com/thebigmunch/gmusicapi-wrapper) now and should already handle this. See [this issue](https://github.com/thebigmunch/gmusicapi-scripts/issues/26) for more information. If there's an still a problem, open up an issue in the wrapper repository.

PS Fuck Apple for naming metadata the same as the file instead of using a different extension.
