### ISSUE TITLE
Add option to delete local file on successful upload

### ISSUE THREAD

**Issue by jaduncan** [thebigmunch/gmusicapi-scripts#35]
I would deeply love this.

Use case is automatic upload with deletion of the local file after each upload success rather than the transfer command failing without any way to know what has and hasn't uploaded.

**Comment by thebigmunch** [comment]
That's actually a pretty awful use for that kind of feature, but it's still something that I might add. As for handling invalid/corrupt files, there's an open issue that you should read.

**Comment by asafge** [comment]
+1

**Comment by thebigmunch** [comment]
@asafge @jaduncan and any others: Question for you, I'm thinking this would be a long CLI option only (--delete-on-success) to prevent any accidents. Especially since the obvious short option would probably be -D which is dreadfully close to the -d dry-run option. Does anybody have an issue with this? If so, I could choose a different short option in an attempt to prevent accidental usage.

**Comment by asafge** [comment]
No problem, sounds like the right way to do that.

**Comment by jaduncan** [comment]
Concurred. Destructive stuff should be difficult to do unintentionally.
