### ISSUE TITLE
gmsync insists on syncing a song despite it being identical

### ISSUE THREAD

**Issue by yacoob** [thebigmunch/gmusicapi-scripts#77]
First of all, thanks for those scripts - as much as I enjoy googlemusic, the default down/up/sync experience is pretty horrible. 

I've ran a test `gmsync -m -d up` from my home collection to GM, and I've discovered that gmusicapi would like to upload some files despite both side having (seemingly) the same information. Specifically, one of the outstanding albums was an album that I've bought recently on GM, then downloaded to local collection. Is there a way to get some information *why* gmsync decided to declare a mismatch? Would a difference in tags be sufficient (even with `-m`)? Adding `-l` doesn't really give me any more information.

**Comment by thebigmunch** [comment]
> First of all, thanks for those scripts - as much as I enjoy googlemusic, the default down/up/sync experience is pretty horrible.

Way to provide a ton of feedback on that one. Most people find the default experience pretty good. I assume you're just being a douchebag based on you having this one issue that's most likely down to you misunderstanding something. It doesn't matter though, because I can choose not to bother with people like you.
