### ISSUE TITLE
Make sync syncing

### ISSUE THREAD

**Issue by VVelda** [thebigmunch/gmusicapi-scripts#83]
Sync functions is one-time upload of file. Is possible to make this really sync, i.e. upload file when file is changed (tag changed) and rewrite original file on server? Or upload that file (at least with some force parameter), when is deleted? I don't know if this is limitaion of app, or API.

Thanks for response

**Comment by thebigmunch** [comment]
That's something you'd right the automation part for. Definitely not something that would go into these scripts.

**Comment by VVelda** [comment]
Then, why is it called (gm)sync? (When it's missing sync)

Is there any automated tool doing this (and using this library eventually)?
I'm thinking, that I might try (definitively not promising) implementing something simple – at least some like "force upload", which does not seem for me something so terrible to be included in this toolset. Are you pro?

**Comment by thebigmunch** [comment]
Because it DOES sync. Think about it like [rsync](https://rsync.samba.org/documentation.html). That is how the sync scripts work. And they do it based on audio file metadata.

But, Google Music doesn't take audio metadata into account when identifying a file; it uses a hash of the audio data. What you seem to want is some daemonized script/application (the automation part you should build yourself) that deletes files on Google Music (only way to force an upload is to not have a song with the same audio hash) as well as re-upload if metadata changes.

For the former, I wouldn't add it even if I wanted to, because it would require the MobileClient to delete on top of the MusicManager to upload. MobileClient doesn't support OAuth in gmusicapi, so it becomes a nuisance. It also would rely on matching the audio hash. gmusicapi's hash generation doesn't match Google's due to limitations in the tooling, so there may be some problems there.

For the latter, you need something that tracks what songs on Google Music are related to local songs. That would requiring you keeping a database for that information. How else would the code know which file to upload if a there's a change on one or the other? Definitely not something I'm interested in building.

Just because you can do something WITH certain software, doesn't mean it has to be IN that software. You have all the tools necessary to build something that does exactly what you want. It just doesn't belong in these scripts.
